### ISSUE TITLE
Invalid argument order

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/aa#3]
A valid BIDS App takes the following positional arguments

1. Position 1: input bids directory
2. Position 2: output directory
3. Position 3: analysis level

However, aa currently takes:
1. Position 1: input bids directory
2. Position 2: XML config file
3. Position 3: XML config file2
4. Position 4: output directory
5. Position 5: analysis level

making it incompatible with the framework. The extra XML files would have to be moved to positions 4 and 5.

**Comment by tiborauer** [comment]
[This commit
](https://github.com/BIDS-Apps/aa/commit/6b47d4c96a7f08425fe281093b2cbbf3d4b803c8
) should solve this issue.

**Comment by tiborauer** [comment]
I close this one.
