### ISSUE TITLE
Lack of documentation about the compulsory XML config files

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/aa#4]
It's hard to use the app not knowing that it would expect.

**Comment by tiborauer** [comment]
I still do not know what is the plan for configuring pipelines.
a. user can provide an XML file
b. user chooses from presets in a drop-down list

**Comment by chrisgorgo** [comment]
b is preferred at the moment

**Comment by tiborauer** [comment]
And what will be the mechnism between the GUI and the code?

**Comment by chrisgorgo** [comment]
For now just document the list of possible options. In the future we will
use boutiques.

**Comment by tiborauer** [comment]
The number of possible options are close to infinite. Do you have a suggestion based on what I should select them? What are the most common use cases?

**Comment by chrisgorgo** [comment]
I don't know as well enough to help with that. Maybe an alternative is a
set of string and numerical optional command line arguments describing
various dimensions of this infinite space?

On Jun 7, 2017 6:39 AM, "Tibor Auer" <notifications@github.com> wrote:

The number of possible options are close to infinite. Do you have a
suggestion based on what I should select them? What are the most common use
cases?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BIDS-Apps/aa/issues/4#issuecomment-306797542>, or mute
the thread

**Comment by tiborauer** [comment]
This one is related to Issue #1 .
